version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            pip install poetry==1.7.1

      - run:
          name: Configure Poetry
          command: |
            poetry config virtualenvs.create false

      - run:
          name: Create Environment
          command: |
            python3 -m venv venv
            source venv/bin/activate

      - run:
          name: Install Pytest Asyncio
          command: |
            pip install pytest-asyncio

      - run:
          name: Install dependencies
          command: poetry install

      - run:
          name: Run tests and generate JUnit XML report
          command: |
            mkdir -p test-results/pytest
            pytest --junitxml=test-results/pytest/junit.xml

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
