version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -

      - run:
          name: Configure Poetry
          command: |
            poetry config virtualenvs.create false

      - run:
          name: Install dependencies
          command: poetry install

      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
